### ISSUE TITLE
install but not working

### ISSUE THREAD

**Issue by ametthey** [Mte90/deoplete-wp-hooks#2]
Hello, 

I have installed it with vim plug
```
 Plug 'mte90/deoplete-wp-hooks', { 'do': './install.sh' }
```

and I detailed the path 
```
let g:wphooks_dir='~/.vim/plugged/deoplete-wp-hooks/wp-hooks/'
```

Must I installed deoplete to make it work ?

**Comment by Mte90** [comment]
Well yes it is a plugin for deoplete.
